#!/usr/bin/env bash
# This script generates an RSA key pair with a 4096-bit key and sets the passphrase to 'betty'.
# The private key will be named 'school' and the public key will be named 'school.pub'.

# Create the RSA key pair
ssh-keygen -t rsa -b 4096 -f school -N "betty"

