#!/usr/bin/env bash
# your script should contain "add_header X-Served-By $hostname;" or else fail. DUMB Intranet.
sudo apt-get update -y;
sudo apt-get install -y nginx;
sudo apt-get install -y ufw;

sudo ufw enable;
sudo ufw allow 'Nginx HTTP';
sudo ufw allow 'OpenSSH';

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html;
custom_header="server_name_;\n\tadd_header X-served-By \$HOSTNAME;"
sudo sed -i "s|server_name_;|$custom_header|" /etc/nginx/sites-enable/default

sudo service nginx restart;
