#!/usr/bin/env bash
# This script transfers a file to a remote server using scp with strict host key checking disabled

# Check if the correct number of arguments are provided
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"

# Use scp to transfer the file to the user's home directory on the remote server
scp -i "$SSH_KEY_PATH" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP":~/

# Check if the scp command was successful
if [ "$?" -eq 0 ]; then
    echo "File successfully transferred to $USERNAME@$SERVER_IP:~/"
else
    echo "File transfer failed. Please check your inputs and try again."
    exit 2
fi

