#!/usr/bin/env bash
# Script to install and configure Nginx on an Ubuntu server

# Check if the script is being run as root
if [ "$EUID" -ne 0 ]; then
	    echo "Please run this script as root or with sudo."
	    exit 1
fi

# Update package list and install Nginx
apt-get update
apt-get install -y nginx

# Create a custom HTML file with the required content
echo "Holberton School" > /var/www/html/index.html

# Configure Nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:80 default_server;/listen [::]:80;/g' /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
service nginx restart
