#!/usr/bin/env bash
# This script installs and configures Nginx on the server

# Update package list and install nginx
apt-get update -y
apt-get install nginx -y

# Ensure Nginx starts with the correct default page
echo "Holberton School for the win!" > /var/www/html/index.html

# Configure Nginx to serve the correct page
systemctl restart nginx

